apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: cql-platform
  labels:
    app: frontend
    app.kubernetes.io/part-of: cql-platform
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
