apiVersion: v1
kind: ConfigMap
metadata:
  name: cql-platform-config
  namespace: cql-platform
  labels:
    app.kubernetes.io/part-of: cql-platform
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DB_URL: "jdbc:postgresql://postgres:5432/cqlplatform"
  FHIR_SERVER_URL: "http://hapi-fhir:8080/fhir"
  FHIR_TERMINOLOGY_URL: "http://hapi-fhir:8080/fhir"
  SERVER_PORT: "8080"
