apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir
  namespace: cql-platform
  labels:
    app: hapi-fhir
    app.kubernetes.io/part-of: cql-platform
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hapi-fhir
