import type { languages } from 'monaco-editor'

export const cqlLanguageConfiguration: languages.LanguageConfiguration = {
  comments: {
    lineComment: '//',
    blockComment: ['/*', '*/'],
  },
  brackets: [
    ['{', '}'],
    ['[', ']'],
    ['(', ')'],
  ],
  autoClosingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  surroundingPairs: [
    { open: '{', close: '}' },
    { open: '[', close: ']' },
    { open: '(', close: ')' },
    { open: '"', close: '"' },
    { open: "'", close: "'" },
  ],
  folding: {
    markers: {
      start: /^\s*\/\/\s*#?region\b/,
      end: /^\s*\/\/\s*#?endregion\b/,
    },
  },
}

export const cqlTokensProvider: languages.IMonarchLanguage = {
  defaultToken: '',
  tokenPostfix: '.cql',

  keywords: [
    'library',
    'version',
    'using',
    'include',
    'called',
    'public',
    'private',
    'parameter',
    'default',
    'codesystem',
    'valueset',
    'code',
    'concept',
    'context',
    'define',
    'function',
    'returns',
    'external',
    'from',
    'where',
    'return',
    'all',
    'distinct',
    'sort',
    'by',
    'asc',
    'ascending',
    'desc',
    'descending',
    'is',
    'as',
    'cast',
    'between',
    'and',
    'or',
    'xor',
    'not',
    'if',
    'then',
    'else',
    'case',
    'when',
    'null',
    'true',
    'false',
    'exists',
    'in',
    'such',
    'that',
    'with',
    'without',
    'let',
    'union',
    'intersect',
    'except',
    'starts',
    'ends',
    'occurs',
    'same',
    'includes',
    'during',
    'included',
    'before',
    'after',
    'within',
    'meets',
    'overlaps',
    'collapse',
    'expand',
    'per',
    'properly',
    'day',
    'days',
    'week',
    'weeks',
    'month',
    'months',
    'year',
    'years',
    'hour',
    'hours',
    'minute',
    'minutes',
    'second',
    'seconds',
    'millisecond',
    'milliseconds',
    'time',
    'timezone',
    'date',
    'datetime',
    'interval',
    'contains',
    'display',
    'predecessor',
    'successor',
    'singleton',
    'point',
    'start',
    'end',
    'width',
    'difference',
    'duration',
    'flatten',
    'combine',
    'first',
    'last',
    'indexof',
    'skip',
    'take',
    'tail',
    'aggregate',
    'convert',
    'to',
  ],

  typeKeywords: [
    'Boolean',
    'Integer',
    'Decimal',
    'String',
    'Date',
    'DateTime',
    'Time',
    'Quantity',
    'Ratio',
    'Code',
    'Concept',
    'Interval',
    'List',
    'Tuple',
    'Choice',
    'Any',
  ],

  fhirResources: [
    'Patient',
    'Encounter',
    'Condition',
    'Observation',
    'Procedure',
    'MedicationRequest',
    'MedicationStatement',
    'MedicationAdministration',
    'DiagnosticReport',
    'ServiceRequest',
    'Immunization',
    'AllergyIntolerance',
    'CarePlan',
    'Goal',
    'Claim',
    'Coverage',
    'Organization',
    'Practitioner',
    'Location',
    'Device',
    'Specimen',
    'Bundle',
    'Composition',
    'DocumentReference',
    'Binary',
  ],

  operators: [
    '=',
    '>',
    '<',
    '!',
    '~',
    '?',
    ':',
    '==',
    '<=',
    '>=',
    '!=',
    '&&',
    '||',
    '++',
    '--',
    '+',
    '-',
    '*',
    '/',
    '&',
    '|',
    '^',
    '%',
    '<<',
    '>>',
    '>>>',
    '+=',
    '-=',
    '*=',
    '/=',
    '&=',
    '|=',
    '^=',
    '%=',
    '<<=',
    '>>=',
    '>>>=',
  ],

  symbols: /[=><!~?:&|+\-*\/\^%]+/,

  escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,

  tokenizer: {
    root: [
      [
        /[a-zA-Z_]\w*/,
        {
          cases: {
            '@keywords': 'keyword',
            '@typeKeywords': 'type',
            '@fhirResources': 'type.identifier',
            '@default': 'identifier',
          },
        },
      ],

      { include: '@whitespace' },

      [/[{}()\[\]]/, '@brackets'],

      [/[<>](?!@symbols)/, '@brackets'],

      [
        /@symbols/,
        {
          cases: {
            '@operators': 'operator',
            '@default': '',
          },
        },
      ],

      [/\d*\.\d+([eE][\-+]?\d+)?/, 'number.float'],
      [/\d+/, 'number'],

      [/[;,.]/, 'delimiter'],

      [/"([^"\\]|\\.)*$/, 'string.invalid'],
      [/'([^'\\]|\\.)*$/, 'string.invalid'],
      [/"/, 'string', '@string_double'],
      [/'/, 'string', '@string_single'],
    ],

    whitespace: [
      [/[ \t\r\n]+/, 'white'],
      [/\/\*/, 'comment', '@comment'],
      [/\/\/.*$/, 'comment'],
    ],

    comment: [
      [/[^\/*]+/, 'comment'],
      [/\/\*/, 'comment', '@push'],
      ['\\*/', 'comment', '@pop'],
      [/[\/*]/, 'comment'],
    ],

    string_double: [
      [/[^\\"]+/, 'string'],
      [/@escapes/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/"/, 'string', '@pop'],
    ],

    string_single: [
      [/[^\\']+/, 'string'],
      [/@escapes/, 'string.escape'],
      [/\\./, 'string.escape.invalid'],
      [/'/, 'string', '@pop'],
    ],
  },
}

export const cqlCompletionItems: languages.CompletionItem[] = [
  {
    label: 'library',
    kind: 14,
    insertText: 'library ${1:LibraryName} version \'${2:1.0.0}\'',
    insertTextRules: 4,
    documentation: 'Declares the library name and version',
  },
  {
    label: 'using',
    kind: 14,
    insertText: 'using ${1:FHIR} version \'${2:4.0.1}\'',
    insertTextRules: 4,
    documentation: 'Imports a data model',
  },
  {
    label: 'include',
    kind: 14,
    insertText: 'include ${1:LibraryName} version \'${2:1.0.0}\' called ${3:Alias}',
    insertTextRules: 4,
    documentation: 'Includes another CQL library',
  },
  {
    label: 'codesystem',
    kind: 14,
    insertText: 'codesystem "${1:Name}": \'${2:http://example.org/codesystem}\'',
    insertTextRules: 4,
    documentation: 'Defines a code system',
  },
  {
    label: 'valueset',
    kind: 14,
    insertText: 'valueset "${1:Name}": \'${2:http://example.org/valueset}\'',
    insertTextRules: 4,
    documentation: 'Defines a value set',
  },
  {
    label: 'code',
    kind: 14,
    insertText: 'code "${1:Name}": \'${2:code}\' from "${3:CodeSystem}" display \'${4:Display}\'',
    insertTextRules: 4,
    documentation: 'Defines a code',
  },
  {
    label: 'parameter',
    kind: 14,
    insertText: 'parameter "${1:Name}" ${2:Type} default ${3:value}',
    insertTextRules: 4,
    documentation: 'Defines a parameter',
  },
  {
    label: 'context',
    kind: 14,
    insertText: 'context ${1|Patient,Practitioner,Encounter|}',
    insertTextRules: 4,
    documentation: 'Sets the evaluation context',
  },
  {
    label: 'define',
    kind: 14,
    insertText: 'define "${1:ExpressionName}":\n  ${2:expression}',
    insertTextRules: 4,
    documentation: 'Defines an expression',
  },
  {
    label: 'define function',
    kind: 14,
    insertText: 'define function "${1:FunctionName}"(${2:params}):\n  ${3:expression}',
    insertTextRules: 4,
    documentation: 'Defines a function',
  },
  {
    label: 'retrieve',
    kind: 14,
    insertText: '[${1:ResourceType}: ${2:valueset}]',
    insertTextRules: 4,
    documentation: 'Retrieves FHIR resources',
  },
  {
    label: 'exists',
    kind: 14,
    insertText: 'exists (${1:expression})',
    insertTextRules: 4,
    documentation: 'Checks if a list has any elements',
  },
  {
    label: 'where',
    kind: 14,
    insertText: 'where ${1:condition}',
    insertTextRules: 4,
    documentation: 'Filters a list based on a condition',
  },
  {
    label: 'sort by',
    kind: 14,
    insertText: 'sort by ${1:field} ${2|asc,desc|}',
    insertTextRules: 4,
    documentation: 'Sorts a list',
  },
  {
    label: 'Measurement Period',
    kind: 14,
    insertText: 'parameter "Measurement Period" Interval<DateTime>\n  default Interval[@${1:2024}-01-01, @${1:2024}-12-31]',
    insertTextRules: 4,
    documentation: 'Standard measurement period parameter',
  },
  {
    label: 'Initial Population',
    kind: 14,
    insertText: 'define "Initial Population":\n  ${1:true}',
    insertTextRules: 4,
    documentation: 'Defines the initial population for a measure',
  },
  {
    label: 'Denominator',
    kind: 14,
    insertText: 'define "Denominator":\n  "Initial Population"',
    insertTextRules: 4,
    documentation: 'Defines the denominator for a measure',
  },
  {
    label: 'Numerator',
    kind: 14,
    insertText: 'define "Numerator":\n  ${1:expression}',
    insertTextRules: 4,
    documentation: 'Defines the numerator for a measure',
  },
] as languages.CompletionItem[]

export function registerCqlLanguage(monaco: typeof import('monaco-editor')) {
  monaco.languages.register({ id: 'cql' })

  monaco.languages.setLanguageConfiguration('cql', cqlLanguageConfiguration)

  monaco.languages.setMonarchTokensProvider('cql', cqlTokensProvider)

  monaco.languages.registerCompletionItemProvider('cql', {
    provideCompletionItems: (model, position) => {
      const word = model.getWordUntilPosition(position)
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      }

      const suggestions = cqlCompletionItems.map((item) => ({
        ...item,
        range,
      }))

      return { suggestions }
    },
  })

  monaco.editor.defineTheme('cql-theme', {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'keyword', foreground: '0000FF', fontStyle: 'bold' },
      { token: 'type', foreground: '267F99' },
      { token: 'type.identifier', foreground: '795E26' },
      { token: 'string', foreground: 'A31515' },
      { token: 'number', foreground: '098658' },
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'operator', foreground: '000000' },
      { token: 'identifier', foreground: '001080' },
    ],
    colors: {
      'editor.background': '#FFFFFF',
      'editor.foreground': '#000000',
      'editorLineNumber.foreground': '#237893',
      'editorCursor.foreground': '#000000',
      'editor.selectionBackground': '#ADD6FF',
      'editor.lineHighlightBackground': '#F7F7F7',
    },
  })
}
