/**
 * CQL Monarch Token Definitions
 *
 * AUTO-GENERATED from official CQL ANTLR grammar (1.5).
 * Source: https://github.com/cqframework/clinical_quality_language
 * Grammar files: scripts/grammar/cql.g4, scripts/grammar/fhirpath.g4
 *
 * DO NOT EDIT MANUALLY.
 * Regenerate: python scripts/generate-monarch-tokens.py
 */

/**
 * All single-word CQL keywords from the `keyword` rule in cql.g4.
 * Used by Monarch tokenizer for syntax highlighting.
 */
export const CQL_KEYWORDS: readonly string[] = [
  'Code',
  'Concept',
  'Interval',
  'List',
  'Tuple',
  'after',
  'aggregate',
  'all',
  'and',
  'as',
  'asc',
  'ascending',
  'before',
  'between',
  'by',
  'called',
  'case',
  'cast',
  'code',
  'codesystem',
  'codesystems',
  'collapse',
  'concept',
  'contains',
  'context',
  'convert',
  'date',
  'day',
  'days',
  'default',
  'define',
  'desc',
  'descending',
  'difference',
  'display',
  'distinct',
  'div',
  'duration',
  'during',
  'else',
  'end',
  'ends',
  'except',
  'exists',
  'expand',
  'false',
  'flatten',
  'fluent',
  'from',
  'function',
  'hour',
  'hours',
  'if',
  'implies',
  'in',
  'include',
  'includes',
  'intersect',
  'is',
  'let',
  'library',
  'maximum',
  'meets',
  'millisecond',
  'milliseconds',
  'minimum',
  'minute',
  'minutes',
  'mod',
  'month',
  'months',
  'not',
  'null',
  'occurs',
  'of',
  'or',
  'overlaps',
  'parameter',
  'per',
  'point',
  'predecessor',
  'private',
  'properly',
  'public',
  'return',
  'same',
  'second',
  'seconds',
  'singleton',
  'sort',
  'start',
  'starting',
  'starts',
  'successor',
  'then',
  'time',
  'timezone',
  'timezoneoffset',
  'to',
  'true',
  'union',
  'using',
  'valueset',
  'version',
  'week',
  'weeks',
  'when',
  'where',
  'width',
  'with',
  'within',
  'without',
  'xor',
  'year',
  'years',
] as const

/**
 * Multi-word CQL keyword phrases from the `keyword` rule.
 * These require special Monarch rules (regex with spaces).
 */
export const CQL_MULTI_WORD_KEYWORDS: readonly string[] = [
  'included in',
  'on or',
  'or after',
  'or before',
  'or less',
  'or more',
  'or on',
  'such that',
] as const

/**
 * CQL type keywords — built-in types and type constructors.
 * Highlighted differently from regular keywords.
 */
export const CQL_TYPE_KEYWORDS: readonly string[] = [
  'Any',
  'Boolean',
  'Choice',
  'Code',
  'Concept',
  'Date',
  'DateTime',
  'Decimal',
  'Integer',
  'Interval',
  'List',
  'Quantity',
  'Ratio',
  'String',
  'Time',
  'Tuple',
  'date',
  'time',
] as const

/**
 * Date/time precision keywords (singular + plural forms).
 * Subset of keywords, useful for specialized highlighting or validation.
 */
export const CQL_DATETIME_PRECISIONS: readonly string[] = [
  'day',
  'days',
  'hour',
  'hours',
  'millisecond',
  'milliseconds',
  'minute',
  'minutes',
  'month',
  'months',
  'second',
  'seconds',
  'week',
  'weeks',
  'year',
  'years',
] as const

/**
 * Reserved words that may NOT be used as identifiers.
 * From the `reservedWord` rule in cql.g4.
 */
export const CQL_RESERVED_WORDS: readonly string[] = [
  'Code',
  'Concept',
  'Interval',
  'List',
  'Tuple',
  'after',
  'aggregate',
  'all',
  'and',
  'as',
  'before',
  'between',
  'case',
  'cast',
  'collapse',
  'convert',
  'day',
  'days',
  'difference',
  'distinct',
  'duration',
  'during',
  'else',
  'exists',
  'expand',
  'false',
  'flatten',
  'from',
  'hour',
  'hours',
  'if',
  'in',
  'is',
  'let',
  'maximum',
  'millisecond',
  'milliseconds',
  'minimum',
  'minute',
  'minutes',
  'month',
  'months',
  'not',
  'null',
  'occurs',
  'of',
  'or',
  'per',
  'point',
  'properly',
  'return',
  'same',
  'second',
  'seconds',
  'singleton',
  'sort',
  'then',
  'to',
  'true',
  'week',
  'weeks',
  'when',
  'with',
  'within',
  'without',
  'year',
  'years',
] as const

/**
 * Grammar metadata for drift detection.
 */
export const CQL_GRAMMAR_META = {
  version: '1.5',
  generatedAt: '2026-03-13T05:36:15Z',
  keywordCount: 115,
  typeKeywordCount: 18,
  reservedWordCount: 67,
} as const
